import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { type ReactNode } from 'react'
import createClient from '@/lib/supabase-server'
import { Navbar } from '@/components/ui/navbar'
import { Toaster } from '@/components/ui/toaster'
import { Sidebar } from '@/components/ui/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({
  children
}: {
  children: ReactNode
}) {
  const supabase = createClient()

  const {
    data: { user }
  } = await supabase.auth.getUser()

  return (
    <html lang="en">
    <body className={inter.className}>
    <ThemeProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem
      disableTransitionOnChange
    >
      {user && (<Navbar user={user}/>)}
      { user && (
      <div className="grid lg:grid-cols-5 2xl:grid-cols-6">
        <Sidebar/>
        <div className="col-span-3 lg:col-span-4 lg:border-l">
          <div className="h-full px-4 py-6 lg:px-8">
            {children}
          </div>
        </div>
      </div>
      )}
      { children }
      <Toaster/>
    </ThemeProvider>
    </body>
    </html>
  )
}
